# TP 0

## 0bjectifs

* Comprendre les bases de la programmation Python :
* Variables, types de données, listes, ensembles et tuples.
* Expressions conditionnelles et boucles
* Trier
* Dictionnaire
* Fichiers et interaction avec les utilisateurs
* Numpy

## Exercice 1

1\. Commentaires


In [1]:
# Ceci est un commentaire
print("Bonjour")

Bonjour


2\. Variables



In [2]:
# une variable
message = "le monde!"
print(message)

le monde!


In [3]:
a = 10
b = 20
c = a + b
print(c)

30


In [4]:
# nombres réels
pi = 3.14
print(pi)

3.14


In [5]:
# types de donnés
message1 = "Bonjour"
a = 12
pi = 3.14
print(type(message1))
print(type(a))
print(type(pi))

<class 'str'>
<class 'int'>
<class 'float'>


3\. Concaténation de deux chaînes de caractères



In [6]:
# Concaténation de deux chaînes de caractères
message = "le monde!"
print("Bonjour" + message)

Bonjourle monde!


In [7]:
# Concaténation de deux chaînes de caractères
message1 = "Bonjour "
message2 = "le monde!"
print(message1 + message2)

Bonjour le monde!


In [8]:
# concaténation de deux variables de types de données différents
# opération + sur deux types de données différents

# Supprimer le commentaire ci-dessous et lancer le code
message1 = "Bonjour en Python"
a = 3
# print(message1 + a)

Pourquoi cette erreur ? Dans le code suivant, nous corrigeons cette erreur.

In [9]:
# solution de concaténation entre deux variables de types de données différents
message1 = "Bonjour en Python "
a = 3
print(message1 + str(a))

Bonjour en Python 3


4\. Listes

In [10]:
a = [10, 20, 30, 40, 50]
print(a)

[10, 20, 30, 40, 50]


In [11]:
a = [10, 20, 30, 40, 50]
print(a[0])
print(a[1])
print(a[2])
print(a[3])
print(a[4])

10
20
30
40
50


In [12]:
# Supprimer le commentaire ci-dessous et lancer le code
a = [10, 20, 30, 40, 50]
# print(a[8])

Nous essayons d'accéder à un élément à un index qui n'existe pas

In [13]:
message1 = "Bonjour en Python "
print(message1[0])
print(message1[1])
print(message1[2])
print(message1[3])
print(message1[4])
print(message1[5])
print(message1[6])
print(message1[7])

B
o
n
j
o
u
r
 


Le code ci-dessus affiche les différents caractères de la chaîne (ou liste de caractères).
Nous allons maintenant obtenir la longueur de cette chaîne.

In [14]:
message1 = "Bonjour en Python "
print(len(message1))

18


Nous allons maintenant créer une liste d'entiers

In [15]:
a = [10, 20, 30, 40, 50]
print(len(a))

5


In [16]:
a = [10, 20, 30, 40, 50]

# ajouter un nouveau numéro à la fin de la liste
a.append(60)
print(a)

[10, 20, 30, 40, 50, 60]


In [17]:
a = [10, 20, 30, 40, 50]

# modifier un numéro à un index donné
a[0] = 0
print(a)

[0, 20, 30, 40, 50]


In [18]:
# Supprimer le commentaire ci-dessous et lancer le code
a = [10, 20, 30, 40, 50]

# a[6] = 20
print(a)

[10, 20, 30, 40, 50]


Pourquoi cette erreur? Nous modifions un élément à un indice inexistant.

In [19]:
a = [10, 20, 30, 40, 50]

# l'insertion d'un élément à un index particulier modifiera la liste
a.insert(0, 0)
print(a)
print(len(a))

[0, 10, 20, 30, 40, 50]
6


In [20]:
a = [10, 20, 30, 40, 50]
a.insert(6, 60)
print(a)
print(len(a))

[10, 20, 30, 40, 50, 60]
6


In [21]:
a = [10, 20, 30, 40, 50]

# Nous allons maintenant essayer d'insérer un nombre à un index plus grand que la longueur
# de la liste. Nous veillerons à ce qu'il n'y ait pas d'erreur et le nouveau numéro
# est ajouté à la fin de la liste
a.insert(10, 60)
print(a)
print(len(a))

[10, 20, 30, 40, 50, 60]
6


5\. Tuples (non-modifiable lists)



In [22]:
a = (10, 20, 30, 40, 50)
print(a)

(10, 20, 30, 40, 50)


In [23]:
a = (10, 20, 30, 40, 50)
print(a[0])

10


In [24]:
a = (10, 20, 30, 40, 50)


# Nous essayons maintenant de modifier un tuple
# Décommentez le code ci-dessous et lancez le code
# Un tupe est une liste non modifiable

# a[0] = 0
print(a)

(10, 20, 30, 40, 50)


6\. Sets



In [25]:
# Un ensemble(Set) est une collection d'éléments distincts

a = {10, 20, 30, 40, 50, 10, 20, 30, 40, 50}
print(a)

{50, 20, 40, 10, 30}


In [26]:
a = {10, 20, 30, 40, 50, 10, 20, 30, 40, 50}
a.add(10)
print(a)

{50, 20, 40, 10, 30}


In [27]:
a = {10, 20, 30, 40, 50, 10, 20, 30, 40, 50}
a.add(60)
print(a)

{50, 20, 40, 10, 60, 30}


In [28]:
a = {10, 20, 30, 40, 50, 10, 20, 30, 40, 50}
a.remove(40)
print(a)

{50, 20, 10, 30}


Nous allons maintenant essayer différents types de données avec les chiffres et afficher le résultat.

In [29]:
# set
a = {10, 20, 30, 40, 50, 10, 20, 30, 40, 50}
print(a)
print(type(a))

# tuple
b = (10, 20, 30, 40, 50, 10, 20, 30, 40, 50)
print(b)
print(type(b))

# list
c = [10, 20, 30, 40, 50, 10, 20, 30, 40, 50]
print(c)
print(type(c))

{50, 20, 40, 10, 30}
<class 'set'>
(10, 20, 30, 40, 50, 10, 20, 30, 40, 50)
<class 'tuple'>
[10, 20, 30, 40, 50, 10, 20, 30, 40, 50]
<class 'list'>


## Exercice 2

1\. Expressions conditionnelles


In [30]:
a = 12
if a % 2 == 0:
    print(a, " is divisible by 2")
else:
    print(a, " is not divisible by 2")

12  is divisible by 2


In [31]:
lang = "Français"
if lang == "Français":
    print("Bonjour le monde!")
else:
    print("Hello World!")

Bonjour le monde!


2\. Boucles

Les boucles peuvent également être utilisées pour accéder aux éléments de différents indices.

In [32]:
# liste
for i in [10, 20, 30, 40, 50, 10, 20, 30, 40, 50]:
    print(i)

10
20
30
40
50
10
20
30
40
50


In [33]:
# tuples
for i in (10, 20, 30, 40, 50, 10, 20, 30, 40, 50):
    print(i)

10
20
30
40
50
10
20
30
40
50


In [34]:
# set
for i in {10, 20, 30, 40, 50, 10, 20, 30, 40, 50}:
    print(i)

40
10
50
20
30


2\. Limites



In [35]:
for i in range(0, 10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [36]:
for i in range(0, 10, 2):
    print(i)

0
2
4
6
8


In [37]:
# print() par défaut affiche le message suivi d'une nouvelle ligne
# Mais vous pouvez changer son comportement

for i in range(0, 10, 2):
    print(i, end=" ")

0 2 4 6 8 

In [38]:
for i in range(10, 0, -2):
    print(i)

10
8
6
4
2


In [39]:
for i in range(10, 0):
    print(i)

split(): La fonction peut être utilisée pour séparer une chaîne de caractères en utilisant 
un délimiteur spécifié. Par défaut, le délimiteur est un espace blanc.

In [40]:
for i in "Bonjour,le,monde!".split():
    print(i)

Bonjour,le,monde!


In [41]:
for i in "Bonjour,le,monde!".split(","):
    print(i)

Bonjour
le
monde!


Write a program in Python to display the following output

  
 1
 
 12
 
 123
 
 1234
 
 12345
 
 123456
 
 1234567
 
 12345678

## Exercice 3

1\. Tri



In [42]:
num = [10, 20, 30, 40, 50, 10, 20, 30, 40, 50]
num.sort()
print(num)

[10, 10, 20, 20, 30, 30, 40, 40, 50, 50]


2\. Tri (ordre décroissant)



In [43]:
num = [10, 20, 30, 40, 50, 10, 20, 30, 40, 50]
num.sort(reverse=True)
print(num)

[50, 50, 40, 40, 30, 30, 20, 20, 10, 10]


3\. minimum



In [44]:
num = [10, 20, 30, 40, 50, 10, 20, 30, 40, 50]
print(min(num))

10


4\. maximum



In [45]:
num = [10, 20, 30, 40, 50, 10, 20, 30, 40, 50]
print(max(num))

50


5\. sorted()

Vous pouvez utiliser cette fonction si vous ne souhaitez pas modifier votre liste initiale par un tri.

In [46]:
num = [70, 20, 30, 10, 50, 60, 20, 80, 70, 50]
tri = sorted(num, reverse=True)
print(num)
print(tri)

[70, 20, 30, 10, 50, 60, 20, 80, 70, 50]
[80, 70, 70, 60, 50, 50, 30, 20, 20, 10]


Modifiez le code donné ci-dessous pour afficher les cinq plus grands numéros uniques.


In [47]:
num = [70, 20, 30, 10, 50, 60, 20, 80, 70, 50]

# sélectionner les cinq premiers numéros
tri = sorted(num, reverse=True)[:5]
print(tri)

[80, 70, 70, 60, 50]


Nous pouvons également utiliser la fonction pour les chaînes de caractères.

In [48]:
print(sorted("Bonjour le monde!".split(), key=str.lower, reverse=True))

['monde!', 'le', 'Bonjour']


## Exercice 4

1\. Dictionnaire



In [49]:
a = {"contente": 12, "content": 12, "triste": 2}
print(a)
print(type(a))

{'contente': 12, 'content': 12, 'triste': 2}
<class 'dict'>


In [50]:
a = {"contente": 12, "content": 12, "triste": 2}
for key in a:
    print("le mot ", key, " apparait ", a[key], " fois")

le mot  contente  apparait  12  fois
le mot  content  apparait  12  fois
le mot  triste  apparait  2  fois


In [51]:
a = {"contente": 12, "content": 12, "triste": 2}
for key, value in a.items():
    print("le mot", key, " apparait ", value, " fois")

le mot contente  apparait  12  fois
le mot content  apparait  12  fois
le mot triste  apparait  2  fois


In [52]:
a = {"contente": 12, "content": 12, "triste": 2}
a["joie"] = 10
print(a)

{'contente': 12, 'content': 12, 'triste': 2, 'joie': 10}


In [53]:
a = {"contente": 12, "content": 12, "triste": 2}
del a["triste"]
print(a)

{'contente': 12, 'content': 12}


In [54]:
mots = {"contente": 12, "content": 12, "triste": 2, "joie": 10}
print(sorted(mots))

['content', 'contente', 'joie', 'triste']


In [55]:
mots = {"contente": 12, "content": 12, "triste": 2, "joie": 10}
mots_tuple = [(key, value) for key, value in mots.items()]
print(mots_tuple)

[('contente', 12), ('content', 12), ('triste', 2), ('joie', 10)]


2\. itemgetter

In [56]:
from operator import itemgetter

mots = {"contente": 12, "content": 12, "triste": 2, "joie": 10}
mots_tuple = [(key, value) for key, value in mots.items()]
print(sorted(mots_tuple, key=itemgetter(1)))

[('triste', 2), ('joie', 10), ('contente', 12), ('content', 12)]


3\. Interaction with user

In [57]:
# nom = input("Quel est votre nom?")
# print(nom)

In [58]:
# age = input("Quel est votre âge? ")
# print(age)
# print(type(age))

In [59]:
# age = input("Quel est votre âge? ")
# age = int(age)
# print(age)
# print(type(age))

**Question:** Ecrire un programme en Python qui interagit avec l'utilisateur pour
obtenir les informations suivantes de 5 étudiants :

- Nom de l'étudiant
- Âge
- Notes en 5 modules

Une fois les informations obtenues pour les cinq étudiants, calculez
et afficher les valeurs suivantes pour chaque module :

- note moyenne
- note maximale
- note minimale

## Exercice 5

Lire et écrire dans un fichier

1\. Fichiers


In [60]:
# écrire dans un fichier
message = "Bonjour le monde"
with open("bonjour.txt", "w") as file:
    file.write(message)
file.close()

In [61]:
# lire un fichier
with open("bonjour.txt", "r") as file:
    text = file.read()
    print(text)
file.close()

Bonjour le monde


In [62]:
# écrire dans un fichier
message1 = "Bonjour le monde"
message2 = "Programmation en Python"
with open("bonjour.txt", "w") as file:
    file.write(message1)
    file.write(message2)
file.close()

In [63]:
# lire un fichier
with open("bonjour.txt", "r") as file:
    text = file.read()
    print(text)
file.close()

Bonjour le mondeProgrammation en Python


In [64]:
# Rédaction dans un fichier en utilisant le caractère de nouvelle ligne
message1 = "Bonjour le monde\n"
message2 = "Programmation en Python"
with open("bonjour.txt", "w") as file:
    file.write(message1)
    file.write(message2)
file.close()

with open("bonjour.txt", "r") as file:
    text = file.read()
    print(text)
file.close()

Bonjour le monde
Programmation en Python


2\. readline()

Cette fonction peut être utilisée pour lire un fichier ligne par ligne et non le contenu complet en un seul appel comme read()

In [65]:
message1 = "Bonjour le monde\n"
message2 = "Programmation en Python"
with open("bonjour.txt", "w") as file:
    file.write(message1)
    file.write(message2)
file.close()

In [66]:
with open("bonjour.txt", "r") as file:
    text = file.readline()
    print(text)
file.close()

Bonjour le monde



In [67]:
message1 = "Bonjour le monde\n"
message2 = "Programmation en Python\n"
with open("bonjour.txt", "w") as file:
    file.write(message1)
    file.write(message2)
file.close()

In [68]:
with open("bonjour.txt", "r") as file:
    for line in file:
        print(line)
file.close()

Bonjour le monde

Programmation en Python



**Question:** Copiez un fichier HTML dans votre répertoire. Ecrire un programme
en Python pour obtenir les valeurs suivantes :

- nombre de caractères dans le fichier HTML
- nombre de lignes dans le fichier HTML
- nombre de mots dans le fichier HTML
- les vingt premiers mots du fichier HTML
- des mots distincts dans le fichier HTML



**Question:** Copier le CSV
du fichier population.csv du dossier **data**. Le fichier contient les valeurs de population entre
1901 et 2016. Écrivez un programme en Python pour obtenir la valeur maximale.

- la valeur maximale de la population
- la valeur minimale de la population


## Numpy

In [69]:
import numpy as np

### Les opérations sur les matrices

In [70]:
a1 = [1, 2, 3, 4]
b1 = [5, 6, 7, 8]

In [71]:
c1 = np.add(a1, b1)
print(c1)

[ 6  8 10 12]


In [72]:
c1 = np.subtract(a1, b1)
print(c1)

[-4 -4 -4 -4]


In [73]:
c1 = np.multiply(a1, b1)
print(c1)

[ 5 12 21 32]


In [74]:
c1 = np.multiply(4, b1)
print(c1)

[20 24 28 32]


In [75]:
c1 = np.dot(a1, b1)
print(c1)

70


In [76]:
c1 = np.dot(5, b1)
print(c1)

[25 30 35 40]


In [77]:
b1 = [5, 6, 7, 8]
c1 = np.dot(a1, b1)
print(c1)

70


In [78]:
a1 = [1, 2]
moyen = np.average(a1)
print(moyen)

1.5


### Tranposition matricielle

In [79]:
b1 = [[5, 6, 7, 8, 9], [1, 2, 3, 4, 5]]
print(b1)
b1 = np.array(b1)
print(b1.T)

[[5, 6, 7, 8, 9], [1, 2, 3, 4, 5]]
[[5 1]
 [6 2]
 [7 3]
 [8 4]
 [9 5]]


### Séparer une matrice en deux, horizontalement et verticalement

In [80]:
a = [[0, 0, 0], [0, 1, 0], [1, 0, 0], [1, 1, 1]]
a = np.array(a)

a = np.hsplit(a, [2])

a1 = a[0]
a2 = a[1]
print(a1)
print(a2)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
[[0]
 [0]
 [0]
 [1]]


In [81]:
a = [[0, 0, 0], [0, 1, 0], [1, 0, 0], [1, 1, 1]]
a = np.array(a)

a = np.vsplit(a, [2])

a1 = a[0]
a2 = a[1]
print(a1)
print(a2)

[[0 0 0]
 [0 1 0]]
[[1 0 0]
 [1 1 1]]


### Les opérations sur les matrices bidimensionnelles

In [82]:
a2 = [[1, 2, 3, 4], [1, 2, 3, 4]]
b2 = [[5, 6, 7, 8], [5, 6, 7, 8]]

In [83]:
c2 = np.add(a2, b2)
print(c2)

[[ 6  8 10 12]
 [ 6  8 10 12]]


In [84]:
c2 = np.subtract(a2, b2)
print(c2)

[[-4 -4 -4 -4]
 [-4 -4 -4 -4]]


In [85]:
c2 = np.multiply(a2, b2)
print(c2)

[[ 5 12 21 32]
 [ 5 12 21 32]]


In [86]:
a2 = [[1, 2, 3, 4], [1, 2, 3, 4]]
a2 = np.array(a2)
b2 = [[5, 6, 7, 8], [5, 6, 7, 8]]
b2 = np.array(b2)
c2 = np.dot(a2, b2.T)
print(c2)

[[70 70]
 [70 70]]


### Redéfinir une matrice

In [87]:
b2.reshape(4, 2)
print(b2)

[[5 6 7 8]
 [5 6 7 8]]


### Créer des matrices avec des nombres aléatoires

In [88]:
a = np.random.rand()
print(a)

0.7229024234580865


In [89]:
a = np.random.rand(1)
print(a)

[0.46120994]


In [90]:
a = np.random.rand(2, 5)
print(a)

[[0.57221181 0.11088852 0.91088523 0.85676384 0.85654346]
 [0.62039134 0.87993032 0.23683632 0.57990326 0.91251225]]


In [91]:
a = np.random.rand(2, 3, 3)
print(a)

[[[0.11479573 0.88361642 0.89804075]
  [0.01497249 0.78445223 0.58317903]
  [0.74712584 0.86805248 0.58813856]]

 [[0.77067505 0.63957001 0.83146907]
  [0.87480008 0.10912798 0.03889539]
  [0.05067832 0.3686462  0.59451283]]]


In [92]:
a = np.zeros(1)
print(a)

[0.]


In [93]:
a = np.zeros(1, dtype=int)
print(a)

[0]


In [94]:
a = np.zeros((2, 5), dtype=int)
print(a)

[[0 0 0 0 0]
 [0 0 0 0 0]]


### Quelques fonctions pour travailler avec des listes

In [95]:
a = [12, 13, 14, 15]
a_reverse = reversed(a)

for num in a_reverse:
    print(num)

15
14
13
12


In [96]:
jours = ["dimanche", "lundi", "mardi", "mercredi", "jeudi", "vendredi"]
jours_num = list(enumerate(jours))
print(jours_num)

jours_num = list(enumerate(jours, start=1))
print(jours_num)

[(0, 'dimanche'), (1, 'lundi'), (2, 'mardi'), (3, 'mercredi'), (4, 'jeudi'), (5, 'vendredi')]
[(1, 'dimanche'), (2, 'lundi'), (3, 'mardi'), (4, 'mercredi'), (5, 'jeudi'), (6, 'vendredi')]


In [97]:
a1 = [1, 2, 3, 4]
b1 = [5, 6, 7, 8]

zipped = list(zip(a1, b1))
print(zipped)

[(1, 5), (2, 6), (3, 7), (4, 8)]


In [98]:
a1 = [1, 2, 3, 4]
b1 = [5, 6, 7, 8]

ezipped = list(enumerate(zip(a1, b1)))
print(ezipped)

[(0, (1, 5)), (1, (2, 6)), (2, (3, 7)), (3, (4, 8))]
